plugins {
    id 'groovy'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'lib', include: '*.jar')
    implementation 'org.codehaus.groovy:groovy:3.0.9'  // Use a stable version like 3.0.9
    implementation 'org.codehaus.groovy:groovy-json:3.0.9'
    implementation 'com.opencsv:opencsv:5.7.1'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'com.oracle.database.jdbc:ojdbc8:19.8.0.0'
    implementation 'org.apache.commons:commons-lang3:3.12.0'
    testImplementation 'org.mockito:mockito-core:3.9.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:3.9.0'
    testImplementation 'org.mockito:mockito-inline:3.9.0'
    testImplementation 'org.powermock:powermock-api-mockito2:2.0.9'
    testImplementation 'org.powermock:powermock-module-junit4:2.0.9'
    implementation 'org.apache.logging.log4j:log4j-api:2.20.0'  // Log4j API
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'

    testImplementation 'org.mockito:mockito-junit-jupiter:4.0.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}

configurations.all {
    resolutionStrategy {
        force 'org.codehaus.groovy:groovy-datetime:4.0.14'  // Force the correct version
    }
}

test {
    useJUnitPlatform()
}
